### ISSUE TITLE
Noftifier performance issues

### ISSUE THREAD

**Issue by Teyler7** [matthewnitschke/ko-dropdown#5]
I have an application that has the same keeps the same dropdown options but the value is being changed from an observable. After about the 6th time the observable is changed, there seems to be a pretty significant slow down. The way I found this was I put some console logs (Judge me all you want) in the  self.dropdownOptions computed function and the self.value.subscribe function. It seemed like they were called way more than they should be.

**Comment by matthewnitschke** [comment]
I would suggest just using a `<select>` element as this dropdown component never really worked the way I wanted it to

**Comment by Teyler7** [comment]
Will do. Thank you.
